### ISSUE TITLE
All one.signal.php config arguments are null

### ISSUE THREAD

**Issue by davidjimenezlopez** [shailesh-ladumor/one-signal#11]
It does not work, in the initConfig function the parameters config returns null. I did not get .env

```
dd(config('one-signal.app_id')) // is null.  On .env set ONE_SIGNAL_APP_ID=4585XXXX-a0XX-XX31-9X7X-3XXXX0dXXXXa9
$this->setUrl(config('one-signal.url')); 
$this->setAppId(config('one-signal.app_id'));
$this->setAuthorization(config('one-signal.authorize'));
$this->setAuthKey(config('one-signal.auth_key'));
 $this->setMutableContent(config('one-signal.mutable_content'));
```

**Comment by ShaileshInfyom** [comment]
have you published the config file? which laravel version are you using?

**Comment by shailesh-ladumor** [comment]
![onne'](https://user-images.githubusercontent.com/16555999/120332909-ce1d9080-c30c-11eb-9ef5-651bf82ca85e.PNG)
@davidjimenezlopez I was tested and working fine. Please check it on your end. make sure not to miss something.
