### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by mackiexx** [shailesh-ladumor/one-signal#19]
Problem 1
    - php-http/guzzle6-adapter[v2.0.0, ..., 2.x-dev] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2, 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by shailesh-ladumor** [comment]
@mackiexx which laravel version are you using?

**Comment by mackiexx** [comment]
Laravel Framework 8.83.4

**Comment by shailesh-ladumor** [comment]
please try `composer require ladumor/one-signal:0.4.1`

**Comment by mackiexx** [comment]
got another error with 0.4.1

Problem 1
    - php-http/guzzle6-adapter[v2.0.0, ..., 2.x-dev] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2, 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by shailesh-ladumor** [comment]
@mackiexx looks like a version conflict with another package.

**Comment by shailesh-ladumor** [comment]
may be with this one `php-http/guzzle6-adapter ^2.0`  please try another version of this package. may be help

**Comment by shailesh-ladumor** [comment]
@mackiexx hope your issue was resolved
