### ISSUE TITLE
Sending push notifications

### ISSUE THREAD

**Issue by RaedElNABOULSI** [shailesh-ladumor/one-signal#28]
How do I send a push notification to all users, or to a specific segment?

**Comment by dbitsdanish** [comment]
function sendNotification(array $deviceIds, string $title, string $subtitle = null, array $data = [])
    {
        try {
            $fields['include_player_ids'] = $deviceIds;
            $fields['headings'] = array(
                'en' => $title,
            );

            if ($subtitle) {
                $fields['contents'] = array(
                    "en" => $subtitle,
                );
            }

            if (!empty($data)) {
                $fields['data'] = $data;
            }

            return OneSignal::sendPush($fields);
        } catch (Exception $e) {
            Log::error('Send Notification Failed: ' . $e->getMessage());
        }
    }

**Comment by dbitsdanish** [comment]
Send notification to specific devices

**Comment by dbitsdanish** [comment]
> How do I send a push notification to all users, or to a specific segment?

Here is the helper function I use to send notification to targeted devices

```php
<?php

use Illuminate\Support\Facades\Log;
use Ladumor\OneSignal\OneSignal;

if (!function_exists('sendNotification')) {
    function sendNotification(array $deviceIds, string $title, string $subtitle = null, array $data = [])
    {
        try {
            $fields['include_player_ids'] = $deviceIds;
            $fields['headings'] = array(
                'en' => $title,
            );

            if ($subtitle) {
                $fields['contents'] = array(
                    "en" => $subtitle,
                );
            }

            if (!empty($data)) {
                $fields['data'] = $data;
            }

            return OneSignal::sendPush($fields);
        } catch (Exception $e) {
            Log::error('Send Notification Failed: ' . $e->getMessage());
        }
    }
}

```

**Comment by shailesh-ladumor** [comment]
@RaedElNABOULSI   you just need to set param like this `$fields['included_segments'] = ["Subscribed Users"]` instead of `include_player_ids` [here](https://github.com/shailesh-ladumor/one-signal#send-push-notification)
