### ISSUE TITLE
Send Push Notification with Tags

### ISSUE THREAD

**Issue by emreiszero** [shailesh-ladumor/one-signal#30]
Hello, how can I send notifications to users with tags? Thank you from now..

**Comment by shailesh-ladumor** [comment]
@emreiszero you can pass `tag` in [this ](https://github.com/shailesh-ladumor/one-signal#send-push-notification)method 
please refer official [docs ](https://documentation.onesignal.com/reference/create-notification#section-result-format-view-notification)
![image](https://github.com/shailesh-ladumor/one-signal/assets/16555999/d55e960e-6198-476a-84cd-07268d19c1ee)
