### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Gapupsa** [shailesh-ladumor/one-signal#7]
i can't install.
please advice.
im using the lates laravel version.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ladumor/one-signal ^3.0 -> satisfiable by ladumor/one-signal[v3.0.2].
    - ladumor/one-signal v3.0.2 requires illuminate/support ~5.0|^6.0|^7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by ShaileshInfyom** [comment]
Which laravel version are you used?

**Comment by ljsharp** [comment]
> i can't install.
> please advice.
> im using the lates laravel version.
> 
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Root composer.json requires ladumor/one-signal ^3.0 -> satisfiable by ladumor/one-signal[v3.0.2].
> - ladumor/one-signal v3.0.2 requires illuminate/support ~5.0|^6.0|^7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Yes me too. I am using the latest version of Laravel ^8.12. 
Any solution to the issue?

**Comment by ShaileshInfyom** [comment]
> > i can't install.
> > please advice.
> > im using the lates laravel version.
> > Your requirements could not be resolved to an installable set of packages.
> > Problem 1
> > 
> > * Root composer.json requires ladumor/one-signal ^3.0 -> satisfiable by ladumor/one-signal[v3.0.2].
> > * ladumor/one-signal v3.0.2 requires illuminate/support ~5.0|^6.0|^7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
> > 
> > Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> 
> Yes me too. I am using the latest version of Laravel ^8.12.
> Any solution to the issue?

ok, I will fix soon

**Comment by shailesh-ladumor** [comment]
@ljsharp @Gapupsa new version released. please try again

**Comment by ljsharp** [comment]
> @ljsharp @Gapupsa new version released. please try again

Okay sure Sir. I will let you know when installed successfully.

**Comment by shailesh-ladumor** [comment]
Ok, thanks

**Comment by ljsharp** [comment]
> @ljsharp @Gapupsa new version released. please try again

The issue has been fixed. Thanks!!

**Comment by NasserFaris** [comment]
I have the same problem.
Your requirements could not be resolved to an installable set of packages.
"laravel/framework": "^8.12"
  Problem 1
    - Root composer.json requires ladumor/one-signal ^3.0 -> satisfiable by ladumor/one-signal[v3.0.2].
    - ladumor/one-signal v3.0.2 requires illuminate/support ~5.0|^6.0|^7.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by mackiexx** [comment]
i have same problem

Problem 1
    - php-http/guzzle6-adapter[v2.0.0, ..., 2.x-dev] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2, 2.x-dev].

**Comment by DevPunit007** [comment]
- Root composer.json requires ladumor/one-signal ^3.0 -> satisfiable by ladumor/one-signal[v3.0.2].
