### ISSUE TITLE
Problem while installing (Laravel 8.36.1)

### ISSUE THREAD

**Issue by Ahmad-Chebbo** [shailesh-ladumor/one-signal#9]
![Capture](https://user-images.githubusercontent.com/41969693/113832285-23b44180-9791-11eb-99ca-66ecca396d27.PNG)

Hello, how can I solve this problem please

**Comment by shailesh-ladumor** [comment]
fixed and released. @Ahmad-Chebbo please try again. Thanks for reporting!!
